name: expense_tracker
description: An appplication that tracks all expenses, and allows you to set budgets and track all details about spending for a more streamlined budget saving plan.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  timezone: ^0.9.1
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  fl_chart: ^0.65.0
  excel: ^2.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  file_picker: ^8.1.0
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.13
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/mipmap-xxxhdpi/expense_tracker.png"

flutter:
  uses-material-design: true
